
### For use with VSCode Rest Client extension

# @urlPrefix = http://localhost:9000
@urlPrefix = https://cold-poetry-5421.us-east1.akkaserverless.app
@customerId = customer-1
@cartId = cart-1
@productId = product-1
@productName = product name 1
@quantity = 1

### cartese.action.ShoppingCartEseTopicOut.AddItem

curl -XPOST -H "Content-Type: application/json" -d '{
  "customer_id": "{{customerId}}",
  "product_id": "{{productId}}",
  "name": "{{productName}}",
  "quantity": {{quantity}}
}' {{urlPrefix}}/ese/cart/{{cartId}}/items/add

### cartese.action.ShoppingCartEseTopicOut.ChangeItem

curl -XPUT -H "Content-Type: application/json" -d '{
  "quantity": {{quantity}}
}' {{urlPrefix}}/ese/cart/{{cartId}}/items/{{productId}}/change

### cartese.action.ShoppingCartEseTopicOut.CheckoutCart

curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ese/cart/{{cartId}}/checkout

### cartese.action.ShoppingCartEseTopicOut.RemoveCart
curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ese/carts/{{cartId}}/remove

### cartese.action.ShoppingCartEseTopicOut.RemoveItem
curl -XPUT -H "Content-Type: application/json" {{urlPrefix}}/ese/cart/{{cartId}}/items/{{productId}}/remove
