/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package cartese.action;

import com.akkaserverless.javasdk.action.ActionCreationContext;

public class ShoppingCartEseTopicOutAction extends AbstractShoppingCartEseTopicOutAction {
  public ShoppingCartEseTopicOutAction(ActionCreationContext creationContext) {
  }

  @Override
  public Effect<ShoppingCartEseActionTopicOut.AddLineItem> addItem(ShoppingCartEseActionTopicOut.AddLineItem addLineItem) {
    return effects().reply(addLineItem);
  }

  @Override
  public Effect<ShoppingCartEseActionTopicOut.ChangeLineItemQuantity> changeItem(ShoppingCartEseActionTopicOut.ChangeLineItemQuantity changeLineItemQuantity) {
    return effects().reply(changeLineItemQuantity);
  }

  @Override
  public Effect<ShoppingCartEseActionTopicOut.RemoveLineItem> removeItem(ShoppingCartEseActionTopicOut.RemoveLineItem removeLineItem) {
    return effects().reply(removeLineItem);
  }

  @Override
  public Effect<ShoppingCartEseActionTopicOut.CheckoutShoppingCart> checkoutCart(ShoppingCartEseActionTopicOut.CheckoutShoppingCart checkoutShoppingCart) {
    return effects().reply(checkoutShoppingCart);
  }

  @Override
  public Effect<ShoppingCartEseActionTopicOut.RemoveShoppingCart> removeCart(ShoppingCartEseActionTopicOut.RemoveShoppingCart removeShoppingCart) {
    return effects().reply(removeShoppingCart);
  }
}
