/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package cartese.action;

import com.akkaserverless.javasdk.action.ActionCreationContext;

import cartese.action.ShoppingCartEseActionTopicOut.AddLineItem;
import cartese.action.ShoppingCartEseActionTopicOut.ChangeLineItemQuantity;
import cartese.action.ShoppingCartEseActionTopicOut.CheckoutShoppingCart;
import cartese.action.ShoppingCartEseActionTopicOut.RemoveLineItem;
import cartese.action.ShoppingCartEseActionTopicOut.RemoveShoppingCart;

public class ShoppingCartEseTopicOutAction extends AbstractShoppingCartEseTopicOutAction {
  public ShoppingCartEseTopicOutAction(ActionCreationContext creationContext) {
  }

  @Override
  public Effect<AddLineItem> addItem(AddLineItem addLineItem) {
    return effects().reply(addLineItem);
  }

  @Override
  public Effect<ChangeLineItemQuantity> changeItem(ChangeLineItemQuantity changeLineItemQuantity) {
    return effects().reply(changeLineItemQuantity);
  }

  @Override
  public Effect<RemoveLineItem> removeItem(RemoveLineItem removeLineItem) {
    return effects().reply(removeLineItem);
  }

  @Override
  public Effect<CheckoutShoppingCart> checkoutCart(CheckoutShoppingCart checkoutShoppingCart) {
    return effects().reply(checkoutShoppingCart);
  }

  @Override
  public Effect<RemoveShoppingCart> removeCart(RemoveShoppingCart removeShoppingCart) {
    return effects().reply(removeShoppingCart);
  }
}
